server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config-yml
  cloud:
    config:
      server:
        git:
          uri: git@github.com:NathanHo1024/Sc.git #GitHub上面的git仓库名字