server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eurekaMaster:8111/eureka/,http://eurekaSliver1:8112/eureka/,http://eurekaSliver2:8113/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept

info:
  app.name: hlgj-microcloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$