server:
  port: 8113
eureka:
  instance:
    hostname: eurekaSliver2 #eureka服务端的实例名称
  client:
    register-with-eureka: false #因为它是主节点（注册中心），不需要向自己注册自己
    fetch-registry: false #false表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务。
    service-url:
     #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与EurekaServer交互的地址查询服务和注册服务
     defaultZone: http://eurekaMaster:8111/eureka/,http://eurekaSliver1:8112/eureka/