server:
  port: 8010

feign:
  hystrix:
    enabled: true


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8111/eureka/,http://localhost:8112/eureka/,http://localhost:8113/eureka/